//This Code has been generated by OpenAI ChatGPT
//Prompts used are listed in-line at the end

from PIL import Image
import os
import numpy as np

# Replace 'path_to_images' with the actual path to your image directory
image_folder = 'D:\\fishmaps'
output_folder = 'D:\\fishmaps'

# Get a list of all PNG files in the directory
image_files = [f for f in os.listdir(image_folder) if f.endswith('.png')]

# Load the first image to get dimensions
first_image = Image.open(os.path.join(image_folder, image_files[0])).convert('L')

# Initialize an accumulator array with zeros
accumulator = np.zeros_like(np.array(first_image), dtype=np.uint64)

# Sum pixel values across all images
for image_file in image_files:
    image_path = os.path.join(image_folder, image_file)
    img = np.array(Image.open(image_path).convert('L'))
    accumulator += img.astype(np.uint64)

# Normalize the accumulated values to the range [0, 255]
stacked_image = (accumulator * 255 / (len(image_files) * 255)).astype(np.uint8)

# Save or display the stacked image
Image.fromarray(stacked_image).save(os.path.join(output_folder, 'stacked_image.png'))

//ChatGPT Prompts Used:
//	I have 171 PNG images that are black and white heatmaps indicating fish density over a given area.  The darker the area the less fish are available.  I would like a way of stacking all the images on top of each other to determine whether there are any hotspots where all kinds of fish are available.
//	For some reason I can't install the package for cv2 is there another way of doing this without it?
//	This code is giving me the following error: line 22, in <module> accumulator += img.astype(np.uint64) ValueError: operands could not be broadcast together with shapes (250,250,4) (250,250,3) (250,250,4)
