//This Code has been generated by OpenAI ChatGPT

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;

public class SerializationExample {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.print("Enter the path or statement: ");
        String pathOrStatement = scanner.nextLine();

        System.out.print("Is it a query? (true/false): ");
        boolean isQuery = scanner.nextBoolean();

        System.out.print("Is it an update? (true/false): ");
        boolean isUpdate = scanner.nextBoolean();

        SatelliteQueryFileFolderUtility utility = new SatelliteQueryFileFolderUtility(pathOrStatement, isQuery, isUpdate);

        // Serialize the object to bytes
        byte[] serializedBytes = serializeObject(utility);

        // Convert the serialized bytes to a hexadecimal string
        String hexValue = bytesToHex(serializedBytes);

        System.out.println("Hex value of the serialized object: " + hexValue);

        scanner.close();
    }

    private static byte[] serializeObject(Object obj) {
        try (ByteArrayOutputStream bos = new ByteArrayOutputStream();
             ObjectOutputStream oos = new ObjectOutputStream(bos)) {
            oos.writeObject(obj);
            return bos.toByteArray();
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    private static String bytesToHex(byte[] bytes) {
        StringBuilder hexString = new StringBuilder(2 * bytes.length);
        for (byte b : bytes) {
            String hex = Integer.toHexString(0xff & b);
            if (hex.length() == 1) {
                hexString.append('0');
            }
            hexString.append(hex);
        }
        return hexString.toString();
    }
}

 
//ChatGPT Prompts Used:
//<pasted full code for SatelliteQueryFileFolderUtility.java>
//	Can you write a program that accepts a path or statement and returns a hex value for the serialised object?
//	Can you modify this to have it accept the path or statement as a user input?
//	Now how do I compile and run this on Linux?
//	What format should I be entering my SQL query in when using SerializationExample.java? can you show me an example of how I would pass on the query "select * from pointing_mode" ?

